---
title: "Flexclust functionality"
author: "Hans Van Calster"
date: "5 maart 2018"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)

opts_chunk$set(echo = TRUE)

library(tidyverse)
library(flexclust)
library(vegan)
options(stringsAsFactors = FALSE)
```

```{r}
# function to reorder clusters in order of descending size
fc_reorder <- function(x, orderby = "decending size") {
  ko <- x
  cl_map <- order(ko@clusinfo$size, decreasing = TRUE)
  ko@second <- cl_map[ko@second]
  ko@clsim <- ko@clsim[cl_map, cl_map]
  ko@centers <- ko@centers[cl_map, ]
  ko@cluster <- cl_map[ko@cluster]
  ko@clusinfo <- ko@clusinfo[cl_map, ]
  # ko@reorder <- cl_map                   add slot with reorder mapping
  return(ko)
}

```



```{r}
set.seed(123456)
data(iris)
iris <- iris %>% 
  tbl_df() %>%
  mutate(Species = as.character(Species), 
         group_of_one = 1:n(),
         species_subset = ifelse(sample(c(TRUE, FALSE), 
                                        size = n(), 
                                        prob = c(0.5, 0.5), 
                                        replace = TRUE) == TRUE, 
                                 Species, 
                                 group_of_one))
```


```{r}
iris %>%
  mutate(in_subset = ifelse(species_subset %in% c("setosa", "virginica", "versicolor"),
                            species_subset, NA)) %>%
  ggplot(aes(x = Sepal.Length, y = Sepal.Width)) + 
  geom_point(aes(colour = Species, fill = in_subset), 
             shape = 21, size = 4)
```



```{r}
means_5 <- kcca(x = iris[,1:4], 
              k = 5, family = kccaFamily("kmeans"),
              group = iris$species_subset)

```

```{r}
table(clusters(means_5), iris$species_subset)
```


```{r}
table(clusters(means_5), iris$Species)
```




```{r}
result <- stepFlexclust(x = iris[,1:4], 
              k = 2:5, 
              nrep = 20, 
              FUN = kcca,
              group = iris$species_subset)

```



```{r}
rec.list <- function(len){
    if(length(len) == 1){
        vector("list", len)
    } else {
        lapply(1:len[1], function(...) rec.list(len[-1]))
    }
}

ks <- 2:5
nreps <- 1:20
models <- rec.list(c(length(ks), length(nreps)))

for (k in ks) {
  for (nrep in nreps) {
    models[[k]][[nrep]] <- kcca(x = iris[,1:4], 
              k = k, family = kccaFamily("kmeans"),
              group = iris$species_subset)
    
  }
}
```



```{r}
#If a cluster gets empty during the iterations it is removed, so you
#can end up with less clusters than you asked for. For grouped
#clustering this happens more often than for regular kmeans because of
#the re-assignement of group members.

#A working example:

set.seed(12)
## same as above
nums <- sample(1:300,70)
x <- matrix(nums,10,7)

## Rows 1, 3 and 4 are in group 1, all other groups contain
## only one observation
mygroups <- c(1,2,1,1,3,4,5,6,7,8)

myfam <- kccaFamily("kmeans", groupFun = "minSumClusters")
clres <- kcca(x, k = 3, myfam, group = mygroups)

clres

table(clusters(clres),mygroups)

```

```{r}
result <- stepFlexclust(x = x, 
              k = 2:5, 
              nrep = 2, 
              FUN = kcca,
              group = mygroups)

```

